/** Recipe inputs panel & dashboard labels. */
export const INPUTS_HE = {
  accordion: {
    dough: "נוסחה ואחוזים",
    flour: "תערובת קמחים",
    starter: "מחמצת וחיוב",
    timing: "תזמון וסביבה",
    ddt: "טמפרטורת בצק יעד ומי לישה",
  },
  fields: {
    doughWeight: "משקל בצק סופי (גרם)",
    hydration: "אחוז הידרציה (מים %)",
    inoculation: "שיעור חיוב — מחמצת (%)",
    salt: "מלח (%)",
    flourPreset: "תערובת מומלצת",
    roomTemp: "טמפרטורת סביבה (°C)",
    hoursToAutolyse: "שעות עד אוטוליזה (שיא מחמצת)",
    coldRetard: "התפחה קרה במקרר (שעות)",
    targetBake: "מועד סיום אפייה",
  },
  actions: {
    calculate: "חישוב מרכיבים",
    share: "שיתוף קישור לנוסחה",
    clearStorage: "איפוס שמירה מקומית",
    starterOnly: "מדריך מחמצת בלבד",
    decreaseWeight: "הפחת משקל",
    increaseWeight: "הוסף משקל",
    decreaseInoculation: "הפחת שיעור חיוב",
    increaseInoculation: "הוסף שיעור חיוב",
    decreaseSalt: "הפחת מלח",
    increaseSalt: "הוסף מלח",
  },
  schedule: {
    title: "מתי הלחם צריך להיות מוכן?",
    subtitle:
      "בחרו מועד סיום אפייה — עבודה פעילה בין 7:00–21:00, עם התאמה לחלונות חסומים.",
    accordion: {
      presets: "מועדים מהירים",
      presetsHint: "בחרו כרטיס — לוח האפייה ייפתח אוטומטית",
      adjustments: "התאמות ללוח",
      adjustmentsHint: "מזג אוויר, טמפרטורה וחלונות חסומים",
      timeline: "לוח אפייה מפורט",
      timelineHint: "שלבים, התראות ומעוררים",
      interactiveDay: "תצוגת יום אינטראקטיבית",
      summary: "סיכום",
    },
    noOptions:
      "אין מועדים מתאימים בזמן שנשאר. השתמשו בזמן מותאם אישית או קיצרו התפחה קרה.",
    customTime: "מועד אפייה מותאם אישית",
    customBakeLabel: "סיום אפייה (יעד)",
    showPlan: "בניית לוח לזמן זה",
    planFooter:
      "התכנון מבוסס על שיעור חיוב {starter}%, {autolyse} שעות עד אוטוליזה, {temp}°C — עדכנו לפי מזג אוויר.",
    fullPlan: "התוכנית המלאה",
    startFeed: "התחלה — האכלת מחמצת",
    bakeTarget: "סיום אפייה (יעד)",
    totalHours: "סה״כ ~{hours} שעות מההאכלה ועד האפייה",
    bulkHours: "התפחה בקערה ~{hours} שעות",
    selectPrompt: "בחרו מועד למעלה כדי לראות שלבים והתראות",
    selected: "נבחר",
    express: "מואץ",
    readyAt: "לחם מוכן: {time}",
  },
  results: {
    emptyTitle: "עדיין לא חושבה נוסחה",
    emptyBody: "הזינו פרמטרים ולחצו «חישוב מרכיבים».",
    flour: "קמח",
    water: "מים",
    starter: "מחמצת",
    salt: "מלח",
    trueHydration: "הידרציה אמיתית",
    flourSplit: "חלוקת קמח",
  },
} as const;
